name: Generate SDK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout the server repository
        uses: actions/checkout@v2
        with:
          repository: carthage-software/server
          path: server

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: cargo build --release
        working-directory: generator

      - name: Install OpenAPI CLI
        run: npm install -g @redocly/openapi-cli

      - name: Bundle the OpenAPI Specification
        run: openapi bundle spec/Specification.yaml --ext json -d -o open-api.json
        working-directory: server

      - name: Generate SDK
        run: |
          ls -la
          ls -la ../
          ls -la ../server
          cargo run -- ../server/open-api.json ../src/lib.rs
        working-directory: generator

      - name: Build
        run: |
          cargo fmt
          cargo build --release

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'chore: re-generate the software development kit'
          branch: main
          commit_user_name: azjezz
          commit_user_email: azjezz@protonmail.com
          commit_author: azjezz <azjezz@protonmail.com>
          file_pattern: 'src/*'
